= Git Introduction
include::../../includes/attributes-settings.adoc[]

== Overview

Version control is everywhere. For example, Google Docs has a way to
https://support.google.com/a/users/answer/9308971?hl=en[check or revert to
earlier file versions]. Git however, is a LOT more powerful than what Google
Docs provides and in this module  we will learn the basics of how to use Git
when developing software.

== Reading

TIP: This section takes an estimated 3-4 hours

* https://git-scm.com/book/en/v2/Getting-Started-About-Version-Control[1.1 About Version Control]
* https://git-scm.com/book/en/v2/Getting-Started-A-Short-History-of-Git[1.2 A Short History]
* https://git-scm.com/book/en/v2/Getting-Started-What-is-Git%3F[1.3 What is Git]
* https://git-scm.com/book/en/v2/Getting-Started-The-Command-Line[1.4 The Command Line]
* https://git-scm.com/book/en/v2/Getting-Started-Installing-Git[1.5 Installing Git]
* https://git-scm.com/book/en/v2/Getting-Started-First-Time-Git-Setup[1.6 First Time Git Setup]
* https://git-scm.com/book/en/v2/Getting-Started-Getting-Help[1.7 Getting Help]
* https://git-scm.com/book/en/v2/Getting-Started-Summary[1.8 Summary]
* https://code.visualstudio.com/docs/terminal/basics[VSCode Terminal Basics]

== Homework

TIP: This section takes an estimated 3-4 hours - The time commitment in this
module can vary widely because you will be downloading and installing tools
which can take more time depending on your personal computing configuration.

* Complete the module reading Quiz (canvas)
* Complete the hands on lab (canvas)

== Retrospective - Class Interaction

TIP: This section takes an estimated 2-3 hours. This includes the time required
to create your own video or discussion post and then watch and read posts from
other students and your instructor.

* Complete the module retrospective assignment (canvas)