= Introduction to Version Control
include::../../includes/attributes-settings.adoc[]

**CS155 Introduction to Version Control (1-0-1)(F,S).** Introduction to the
central ideas, practices, and day to day usage of software version control
using Git. Basic client side usage such as  committing, branching, merging, and
pull-requests will be explored. COREQ: CS153.

== Topics

[cols="5,~"]
|===
|Module| Topic

|0| xref:course-introduction.adoc[Course Introduction]
|1| xref:git-introduction.adoc[Git Introduction]
|2| xref:git-basics.adoc[Git Basics]
|3| xref:git-branching-and-merging.adoc[Branching and Merging]
|4| xref:github.adoc[GitHub]
|===

== Course Learning Outcomes

By the end of this course the student should have achieved the following course
learning outcomes.

[%header,format=csv]
[cols="10,10,~,15,15"]
|===
include::learning-objectives.csv[]
|===

* https://cft.vanderbilt.edu/guides-sub-pages/blooms-taxonomy/[Blooms Taxonomy]
* https://tips.uark.edu/blooms-taxonomy-verb-chart/[Booms Taxonomy of Verbs]

== Course Materials

* https://git-scm.com/book/en/v2[Pro Git (2nd edition)]
* https://drive.google.com/file/d/1nJ0XC0H7eI5I_g9WCqY9v-LlBMREaRBe/view?usp=share_link[The Linux Command Line]
* https://www.youtube.com/playlist?list=PLFziFbk-D-X3wbyZiKOu5aEcf9NGFUj8R[Course Videos]
* https://github.com/shanep?tab=repositories&q=250&type=&language=&sort=[Labs]


== Assessments

Your final grade will be calculated with the following weights in canvas.

* Quizzes - 35%
* Participation - 10%
* Assignments - 35%
* Final - 20%

=== Quizzes

There will be several quizzes over the assigned reading and general git usage.
The quizzes are open notes and open book and must be done individually.

=== Participation

This is an online asynchronous class, thus all of our interactions and
participation will be done through canvas using discussion boards and video
posts.

=== Assignments

This class is centered around hands on practice. There are several
https://github.com/shanep?tab=repositories&q=250&type=&language=&sort=[Hands on
Labs] that you will work on each week. You will get credit for doing the labs
through canvas quizzes.

NOTE: All homework in this class can be done with tools that are installed
locally, you don't have to use any remote or cloud based tools.

=== Final

We will have a take home final exam that must be done individually.

include::../../includes/syllabus-boiler.adoc[]
