= Cross Platform
include::../../includes/attributes-settings.adoc[]

Notes for developing cross platform applications with C/C++ and cmake using the
https://github.com/shanep/cpp-project-template[cpp-project-template]. While the
project template is configured to download and install some of the required
dependencies each operating system still needs to have some tools installed to
proceed. The following sections will help you install the required dependencies
for each operating system.

== ✅ Instructor support systems

Your instructor and GA/TA will support the Kount Lab, Onyx and GitHub
codespaces. If you are working in the lab follow the instructions in the
https://github.com/shanep/cpp-project-template/blob/master/README-KOUNT-LAB.md[CS
Lab] document. Otherwise you can use
https://docs.github.com/en/codespaces/getting-started/quickstart[GitHub
Codespaces] to work on your projects.

=== VSCode Notes

The VSCode CMake extension (2023-10-17) does not support all the features of
cmake presets that this project uses so you will need to add the following to
your settings.json file so that the extension does not complain about the
new features we are using.`"cmake.allowUnsupportedPresetsVersions": true`.

* https://code.visualstudio.com/docs/getstarted/settings[VSCode Settings]


== ⚠️ Tested but Unsupported

The systems listed below have been tested by your instructor to work at one
point in time. However, due to the high number of permutations that students
personal systems can come in all systems listed below are **not supported**. If
you can not get your personal system to work then you will need to work in
either codespaces or in the CS Lab.

NOTE: Every Semester new issues pop up because of software upgrades and other
changes that are outside of your instructors control so if you encounter any
errors please let your instructor know what you did to fix the problem so this
section can be updated for other students 😃.

=== Fedora 38+

* sudo dnf group install "Development Tools"
* sudo dnf install libasan lcov readline gtest-devel gtest

=== Windows 11+

* Install https://visualstudio.microsoft.com/downloads/[Visual Studio 2022]
  Community Edition Select "Desktop development with C++" when prompted.
* https://learn.microsoft.com/en-us/cpp/build/cmake-projects-in-visual-studio?view=msvc-170[Learn about cmake in VS2022+]

=== MacOS 13.5.2+

* Install https://brew.sh/[homebrew]
* Install https://apps.apple.com/us/app/xcode/id497799835?mt=12[Xcode]
* xcode-select -install to install Command Line Tools.
* brew install cmake googletest

=== Ubuntu 22.04 +

* sudo apt-get upgrade
* sudo apt install build-essential manpages-dev
* sudo snap install cmake --classic
* sudo apt-get install git
* sudo apt-get install libreadline-dev

== ❌ Untested Systems

The following systems have been deprecated and are no longer tested or supported.
If you are running one of the systems below you should upgrade to a more recent
system.

* Windows 10
* Ubuntu 20.04