= Grading Rubric
include::../../includes/attributes-settings.adoc[]

Grades for programming projects will be assigned according to the rubric below.
Each criterion is clearly detailed in the following sections. Make sure and read
through each section as examples are given for each criterion.

== Minimum standards

Your code must meet the two minimum standards of compiling and correctness in
order to be graded. If your program fails to meet these standards it will not be
graded and a score of 0 will be assigned.

=== Compiling

Unless otherwise stated all code must compile and run on the department's
computers in the Kount Computer Lab (CCP241) and using github codespaces. You
are responsible for ensuring your code compiles in both locations. You can
access the lab computers remotely via ssh or you can go to the lab and use a
workstation directly. https://github.com/features/codespaces[GitHub Codespaces]
is free to use for up to 60 hours per month and can be accessed with any modern
browser.

All code will be compiled and tested on the command line using the scripts
provided. Your instructor or teaching assistant will *not* use an IDE to build
and test your code. While you are welcome to use any IDE you wish to develop
your code it is strongly recommended that you compile and test your code using
the terminal to ensure you have not introduced any IDE specific dependencies on
accident.

All Header files and interfaces must be implemented as specified. You are not
allowed to change the header files in any way. Header files will be reset to
their default state when grading.

== Grading Rubric

|===
| Criterion | Percentage | Expert (1) | Proficient (.9) | Apprentice (.8) | Novice (.7) | Unknown (0)

| <<Testing>>
| 50%
| Passes 100% of instructor test suite
| Passes between 90% and 99% of instructor test suite
| Passes between 80% and 89% of instructor test suite
| Passes less then 80% of instructor test suite
| Unable to test or Minimum standards were not meet

| <<Code Quality>>
| 30%
| No issues with code quality
| One issue
| Two issues
| More than two issues
| Unable to test or Minimum standards were not meet

| <<Documentation>>
| 10%
| Perfect documentation
| One issue
| Two issues
| More that two issues
| No documentation was done or Minimum standards were not meet

| <<Retrospective>>
| 10%
| ALL TODO's are done and minimum word count was met
| ALL TODO's are done but did not meet the minimum word count
| Most TODO's are done
| N/A
| Unable to test or Minimum standards were not meet


| <<Security>>
| 10%
| Secure programming techniques are correctly applied
| One secure programming violations
| Two secure programming violations
| More than two secure programming violations
| Secure programming techniques are not correctly applied or Minimum standards were not meet
|===

== Security

All C/C++ code must conform to the following standards.

* Students must address all memory leaks
* Students must address any double free errors
* Students must not have any dangling pointers in their code
* All out of bounds read/write errors must be addressed.
* https://github.com/git/git/blob/master/banned.h[Banned Functions]

All projects are configured with a debug option that sets the appropriate
compiler flags for you! Make sure and run all your tests under both debug and
release builds.

include::../../includes/grading-rubric-boiler.adoc[]
