= Research Paper
:toc: left

== Overview

A research paper is intended to provide the student with an opportunity to
explore a topic relevant to what is being taught in the class. It is important
that you begin your research early. The first step is to choose a topic that is
of interest to you or you can use the default topic detailed below. If you are
choosing a custom topic, you should consult with your instructor to make certain
that your topic fits within their expectations for the assignment.

== Default topic - Zero Day Vulnerabilities

A zero day is a computer-software or hardware vulnerability previously unknown
and is used by malicious actors to write malware. The list below is a good
starting point to help you understand what a zero day vulnerabilities is and
some real world examples that you can explore.

* Simple google search for zero day
* https://scholar.google.com/scholar?hl=en&as_sdt=0%2C13&q=zero+day&btnG=[Google scholar]
* https://googleprojectzero.blogspot.com/[Google project zero]
* https://learn.microsoft.com/en-us/microsoft-365/security/defender-vulnerability-management/tvm-zero-day-vulnerabilities?view=o365-worldwide[Microsoft]
* https://zerodium.com/[Zerodium]
* https://en.wikipedia.org/wiki/Zero-day_(computing)[zero day vulnerabilities] 

Below are a few high profile examples from the last few years. You are welcome
to use one of these in your paper.

* https://heartbleed.com/[Heartblead]
* https://en.wikipedia.org/wiki/Shellshock_(software_bug)[Shell shock]
* https://meltdownattack.com/[meltdownattach]
* https://en.wikipedia.org/wiki/Row_hammer[Row hammer]

=== Zero day Discussion

This is the meat of your paper. Each student in the team will need to identify 1
high profile *zero day vulnerabilities* that have happened in the last 10 years
and find out the following:

* What piece of software did they impact?
* What Operating system was it present on?
* Was it Network related?
* Firmware Hardware
* Was it a https://www.kaspersky.com/resource-center/definitions/what-is-zero-click-malware[zero click exploit?]
* Was customer data breached?

== Custom topic

You are allowed to research any relevant topic that was introduced in class.
The research paper and associated presentation is due at the end of the semester
so you have some time to explore different areas that you may be interested in.

== Paper outline

Mid semester you will be required to submit an outline that details the high
level direction of the paper. An example outline is shown below to help guide
you. Each section needs to be assigned to a specific person in the team. Each
team member will be responsible for their assigned work. Your final grade on
the paper will be an individual grade based on your efforts and will not be
impacted by team mates that don't pull their weight. The example shown below
assumes that there is a team of 3, for a team of two there would be only two
subtopics instead of 3.

* Introduction (Joe)
** Introductory Statement (Jane)
** Thesis Statement (Jill)
* Body (Joe, Jane, Jill)
** First Subtopic (Joe) 
*** supporting evidence
** Second Subtopic (Jane)
*** supporting evidence
** Third Subtopic (Jill)
*** supporting evidence
* Conclusion (Jill)
** Restatement of Thesis (Joe)
** Compelling Conclusion (Jane)

== Research Paper Instructions

Your paper will be checked for plagiarism automatically by canvas. Make sure and
cite all your sources as appropriate. Your paper should be a minimum of 2,500
words with a maximum of 5,000 words. Citations can be in either MLA or APA
format.

=== References

You need to cite all your sources that you found and used to construct your
paper, you need a minimum of 5 sources.

== Checklist for Papers

* Organization
* Does the paper follow the outline that you submitted before?
* Is the paper double spaced?
* Did you run spell checker?
* Are all papers cited in the text found in the References (and vice versa)?
* Have major points been backed up with appropriate references rather than
forcing the reader to take my word for it?
* Are any tables and figures organized to minimize space?
