= C Review ðŸ”¥
Shane K. Panter <shanepanter@boisestate.edu>
:toc: left
:date: 2023-05-04
:revealjsdir: /reveal.js
:source-highlighter: highlightjs
:icons: font

== Overview

This is a quick review of what was taught in CS253!

WARNING: If you have not written much C lately now is a good time to shake the
cobwebs off!

== Types, Operators, and Expressions

The C language provides only a few basic type specifiers: char, int, float and double.

== Control flow

Control flow in C is similar to java with some of the same gotyas (like switch statements falling
through without an explicit break). You have If-Else, Else-If, Switch, loops (while, for, do/while),
break, continue and the infinitely-abusable *goto* statement.

== Header Files

Java has no notion of a "header file" in the same way as the C language does. However, we can make
*rough* comparisons between a C header file (ending in a .h) and a https://docs.oracle.com/javase/tutorial/java/concepts/interface.html[Java
interface].

== Static Variables

[,c]
----
/* foo is private to this source file */
static int foo;

/* bar is private to this source file */
static void bar(void){ ... }

static void foobar(void)
{
  /*
  var is private to foobar and will
  retain its value across func calls
  */
  static int var;
}
----

== Pointers and Arrays â˜ ï¸

[,c]
----
int x=1, y=2, z[10]
int *ip; /* ip is a pointer to int */

ip = &x; /* ip now pointers to x */
y = *ip /* y is now 1 */
*ip = 0 /* x is now 0 */
ip = &z[0] /* ip now points to z[0]*/
----

=== Address Arithmetic

[,c]
----
int stuff[10]
int *ip = &stuff

//what does adding 1 to ip mean?
ip = ip +1;
----

== Strings

There is no explicit string type in C like there is in Java. In C a string is just an array of
*chars* that are terminated with a null character ('\0').

WARNING: Remember C doesn't do any bounds checking!!

== Structures

[,c]
----
/* Define a new struct type called foo */
struct foo{
    int a;
    int b;
};
/* Declare a new variable named bar of type struct foo */
struct foo bar;
----

=== Pointers to Structures

[,c]
----
struct point foo;
struct point *fooptr = &foo;

/* Access x and y with struct var */
foo.x;
foo.y;

/* Access x and y with struct pointer */
fooptr->x;
fooptr->y;
----

== Compiling

Little different than what we do in Java!

* Compiling errors - Same is Java this is a syntax error
* Linking errors - Similar to class loading errors in Java
* Runtime errors - Same as Java this is errors in your logic

=== Linking error

Linking errors trip up new C programmers the most.

[,bash]
----
Undefined symbols for architecture arm64:
  "_go", referenced from:
      _main in main.cpp.o
ld: symbol(s) not found for architecture arm64
----

== Debugging

* Must build a with the debug flag
* Don't turn on any optimizations
* You can use the Command line or VSCodes Integrated debugger

== Questions?

== Demo

Let's write the hello world and play around with it in class!

* https://github.com/shanep/os-hello-world[OS Hello World]