#+SETUPFILE: ../../level-1.org
#+TITLE: Week 2 - Developer Setup
#+SUBTITLE: CS408 Full Stack Web Development
#+DESCRIPTION: CS408 Full Stack Web Development


* Overview

The first few weeks of this class will be a review of CS208 where we will shake the cobwebs out of
our head and also introduce some new terms. This week we will discuss how the Internet works at a
high level and how data is shared over the World Wide Web (WWW). We will also do a scavenger hunt so
we can get familiar with the course materials and practice creating and uploading our first patch.

Important topics that this week covers:

- Web History
- IP addresses, domain names, and URLs
- HTTP
- Web trends
- Introduction to HTML
- Introduction to CSS
- Introduction to JavaScript

* Reading

- [[https://developer.mozilla.org/en-US/docs/Learn/Common_questions/Web_mechanics/How_does_the_Internet_work][How does the Internet work]]
- [[https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web/How_the_Web_works][How the Web Works]]
- [[https://www.youtube.com/watch?v=wkgPvezGpX8][Canvas Peer Review]]

* Lab
:PROPERTIES:
:custom_id: lab
:END:

Given the open nature of the web programming assignments in this class will be a bit different than
other courses. You will be completing each lab individually and then uploading your work as a patch
file for other students to give feedback on. The purpose of the lab assignments is to prepare you
for the midterm and final exams. You are allowed to collaborate on any of the lab projects as much
as you wish.
