#+SETUPFILE: ../../level-1.org
#+TITLE: Week 1 - Introduction
#+SUBTITLE: CS408 Full Stack Web Development
#+DESCRIPTION: CS408 Full Stack Web Development
#+options: toc:nil

* Welcome!

Hello! My name is Shane Panter and I will be your instructor for this class. In this class we will
continue where CS208 left off learning about Full stack web development.  This course has been
designed to take someone who has been introduced to basic full stack concepts and introduce some more
advanced concepts.  In order to succeed in the course, it will be critical for you to manage your
time effectively and keep up with the reading, integrated activities and discussion forum posts.
Please take the time to review your course schedule for this semester to ensure you'll be able to
dedicate the time necessary to be successful in the course.

This course has been carefully divided into small manageable chunks of work that you need to
complete each week. To complete this course start with week 1 then move to week 2, etc. If you have
any questions or concerns please contact me through email or canvas. I look forward to interacting
with you online this semester!

#+begin_export html
<iframe width="560" height="315" src="https://www.youtube.com/embed/FshUPVADcu4?si=QnJOoH3zRhhS9S6-"
title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write;
encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
#+end_export

After watching the introduction video linked above log into [[https://canvas.boisestate.edu/][canvas]] and get started on the
assignments in the week 1 in the module section.

* Communication

Even though many of us are very accustomed to communicating via email, text, and discussion forum,
there is still a lot that can get lost in translation when communicating online. Additionally, as
you've likely seen on social media, news sites, etc., the standards of professionalism and kindness
that many have for in-person conversations do not always show up in digital conversations. Because
the vast majority of communication for this class will occur via email and Canvas discussions, it's
crucial that we remain aware of the challenges of talking online and make every effort to remain
professional, courteous, and clear.

We will adhere to Netiquette in this class, which is a set of guidelines that help facilitate
appropriate and civil online conversation. Please contact me if you have questions or believe anyone
is not acting in accordance with these core rules.

- Make meaningful contributions
- Respond to others with respect
- Provide constructive feedback
- Avoid overly negative criticism
- Be conscious of the tone of your text

* Tasks

In this course, we will explore how websites work, their structure, and how information is
communicated across the Internet. Web development consists of a lot of different technologies that
were all developed at different times. What makes web development hard is the vast number of
languages, frameworks, and standards that all somehow fit together to create what we think of as the
"Modern Web". Additionally, web development changes very rapidly so what is the new hot thing today
will be considered obsolete in a few years. This class doesn't teach frameworks, this class teaches
the fundamentals that are used to build everything else. If you understand the fundamentals you can
learn any framework that you may need.

** Review and Explore

For this task, all you need to do is explore the site. Click through all the links and see if you can
find anything that is missing or broken! You can get extra credit for any typo you find on the
course website. Read all the class policies to make sure you are familiar with what is expected of
you during the semester.

**  Canvas

Complete the following assignments this week on canvas

- Syllabus Quiz (canvas)
- Class Introduction (canvas)
