#+SETUPFILE: ../../level-2.org
#+TITLE: Branching and Merging
#+SUBTITLE: CS155 Introduction to version Control
#+DESCRIPTION: CS155 Introduction to version Control
#+DATE: <2017-01-01 Mon 08:00>

* Overview
:PROPERTIES:
:CUSTOM_ID: branching-and-merging
:END:
This module will introduce two powerful concepts, branching and merging.
Git provides a solid set of commands that allows developers to work on
several different versions of the code at once. These distinct versions
are called branches. Branches may consist of a new feature, a bug that
you need to isolate, or numerous other reasons to create a separate
branch of code. We will leverage Git's fantastic branching and merging
features in this module.

* Reading
:PROPERTIES:
:CUSTOM_ID: reading
:END:
This section takes an estimated 3-4 hours

- [[https://git-scm.com/book/en/v2/Git-Branching-Branches-in-a-Nutshell][Branches in a Nutshell]]
- [[https://git-scm.com/book/en/v2/Git-Branching-Basic-Branching-and-Merging][Basic Branching and Merging]]
- [[https://git-scm.com/book/en/v2/Git-Branching-Branch-Management][Branch Management]]
- [[https://git-scm.com/book/en/v2/Git-Branching-Branching-Workflows][Branching Workflows]]
- [[https://git-scm.com/book/en/v2/Git-Branching-Remote-Branches][Remote Branches]]
- [[https://git-scm.com/book/en/v2/Git-Branching-Rebasing][Rebasing]]
- [[https://git-scm.com/book/en/v2/Git-Branching-Summary][Summary]]

While the reading workload is less than other modules, these concepts
are by far the most difficult to understand so take your time, it will
be worth it!

* Homework
:PROPERTIES:
:CUSTOM_ID: homework
:END:
This section takes an estimated 3-4 hours

- Complete the module reading Quiz (canvas)
- Complete the hands on lab (canvas)

* Retrospective - Class Interaction
:PROPERTIES:
:CUSTOM_ID: retrospective---class-interaction
:END:
This section takes an estimated 2-3 hours. This includes the time
required to create your own video or discussion post and then watch and
read posts from other students and your instructor.

- Complete the module retrospective assignment (canvas)
