#+SETUPFILE: ../level-0.org
#+TITLE: Shane K. Panter
#+SUBTITLE: Curriculum Vitae
#+DESCRIPTION: Shane K. Panter's CV


* Education

- Ph.D. in Computing, Computer Science Emphasis, Boise State University, 2026 (est)
- M.S.  in Computer Science, Boise State University, 2013

* Academic Appointments

- **August 2023 - Present** Clinical Assistant Professor, Boise State University
- **August 2021 - August 2023** Lecturer III, Boise State University
- **August 2013 - August 2021** Lecturer II, Boise State University
- **March 2009 - May 2011** Research Assistant, Boise State University

* Industry Experience

- **September 2012 - Present** Senior Software Engineer, Foundation Code
- **May 2011 - September 2012** System Firmware Engineer, Hewlett Packard
- **June 2005 - May 2011** Software Developer / Cybersecurity, Western Trailer
- **August 2002 - June 2005** Network Technician, Price Electric

* Publications

- A. Joshi, M. Schmidt, **S. Panter** and A. Jain, "Evaluating the Benefits of Team-Based Learning in a
  Systems Programming Class," 2020 IEEE Frontiers in Education Conference (FIE), Uppsala, Sweden,
  2020, pp. 1-7, doi: 10.1109/FIE44824.2020.9274183.
- Klabo, Trevor M.; Valdez, Tyler; Whitehead, Trevin; Petitmermet, Nicholas; Young, Callum; Moll,
  Amy; Salzman, Noah; Stieha, Vicki; **Panter, Shane**; and Latta, Susan, "Assistive Technology: Robot
  Arm" (2020). 2020 Undergraduate Research Showcase. 96.
- **Panter S.**, Schmidt M., Jain A. Team Based learning in Computer Science. Poster presented at
  Great Ideas for Teaching and Learning Symposium. 2014

* Grants

- NSA “GenCyber 2024 Summer Camp at Boise State University for Secondary Teachers,” PI: Jyh-haw Yeh
  (Program Director), Co-PIs: Doug Twitchell, **Shane Panter** and Edward Vasko, 7/24/2023-7/24/2025,
  $150K.

* Teaching
** Undergraduate

- CS117 C++ for Engineers - **Course coordinator** (Fall 2015 - Present)
- CS119 Introduction to Java
- CS121 Introduction to Computer Science I
- CS155 Introduction to Version Control - **Course coordinator** (Spring 2018 - Present)
- CS208 Introduction to Full Stack Web Development - **Course coordinator** (Spring 2023 - Present)
- CS221 Introduction to Computer Science II
- CS253 Introduction to Systems Programming - **Course coordinator** (Fall 2015 - Spring 2018)
- CS333 Network Security and Defense **Course coordinator** (Spring 2023 - Present)
- CS354 Programming Languages
- CS401 Introduction to Web Development - **Course coordinator** (Spring 2020 - Present)
- CS452 Operating Systems - **Course coordinator** (Fall 2019 - Present)
- CS471 Software Engineering
- CS481 Senior Design - **Course coordinator** (Spring 2018 - Spring 2021)

** Graduate

- CS516 Introduction to Web Development - **Course coordinator** (Spring 2020 - Fall 2023)
- CS552 Operating Systems - **Course coordinator** (Fall 2019 - Present)

** Courses Developed
- CS117 C++ for Engineers
- CS155 (250) Introduction to Version Control
  - Collaborated with Dr. Bogan Dit
- CS208 Introduction to Full Stack Web Development
  - Collaborated Dr. Bogan Dit
- CS221 Introduction to Computer Science II (Online Version)
  - Collaborated with Mason Vail
- CS253 Introduction to Systems Programming
  - Collaborated with Dr. Amit Jain and Marissa Schmidt
- CS408 Full Stack Web Development
- CS481 Senior Design

* Service

- **Spring 2023 - Present** Idaho Cyber Range liaison for Boise State University
- **Spring 2023 - Present** Computer Science Department Outreach Committee member
- **Spring 2017 - Spring 2023** Computer Science Department Curriculum Committee member
- **Spring 2019 - Spring 2021** Industry liaison for CS481 - senior design
- **Spring 2019 - Spring 2021** Committee Member University Foundations Finishing Foundations courses
- **Spring 2019 - Spring 2021** Committee member COEN Senior design committee
- **Spring 2017 - Spring 2018** **Interim Chair** of the Computer Science Department Curriculum Committee
- **Spring 2016** **Chair** of the EN-0020-15 Lecturer search committee

* Volunteer Service

- **Spring 2017 - Present** Business Professionals of America (BPA) Judge
- **Fall 2019 - Fall 2021** IHSAA speech and debate Judge
- **Fall 2015 - Spring 2016** Lowell Scott CS Club instructor
