= CS452/552 Grading Rubric
include::../../../includes/attributes-settings.adoc[]

Grades for programming projects will be assigned according to the rubric below.
Each criterion is clearly detailed in the following sections. Make sure and read
through each section as examples are given for each criterion.

== Minimum standards

Code that fails to compile will not be graded and will be assigned a score of 0.
Unless otherwise stated all code must compile on **onyx.boisestate.edu**.  You
can complete all the assignments using a virtual machine or your own computer
but you should do your final testing in the lab. To be clear if your project
works on your machine and **not** in the lab you will still receive a 0.

All code will be compiled and tested on the command line using the scripts
provided. Your instructor or teaching assistant will *not* use an IDE to build
and test your code. While you are welcome to use any IDE you wish to develop
your code it is strongly recommended that you compile and test your code using
the terminal to ensure you have not introduced any IDE specific dependencies on
accident.

WARNING: Intentionally modifying the tests given to you in order to get your
project to pass is considered academic dishonesty and will be dealt with
accordingly. If you think you have found a legitimate bug in the provided tests
you **must** attend office hours to discuss.

== Grading Rubric

|===
| Criterion | Percentage | Expert (1) | Proficient (.9) | Apprentice (.8) | Novice (.7) | Unknown (0)

| <<Testing>>
| 50%
| Passes 100% of the provided test suite
| Passes between 90% and 99% of the provided test suite
| Passes between 80% and 89% of the provided test suite
| Passes less then 80% of the provided test suite
| Unable to test or Minimum standards were not meet

| Code Coverage
| 20%
| Between 80% and 100% coverage of lines and functions
| Between 70% and 79% coverage of lines and functions
| Between 60% and 69% coverage of lines and functions
| Between 50% and 59% coverage of lines and functions
| Less than 50%

| <<Code Quality>>
| 10%
| No issues with code quality
| One issue
| Two issues
| More than two issues
| Unable to test or Minimum standards were not meet

| Compiling
| 10%
| No Warnings
| 1 or 2 Warnings
| 3 or 4 Warnings
| 4 or 5 Warnings
| More than 5 warnings

| <<Retrospective>>
| 10%
| ALL TODO's are done and minimum word count was met
| ALL TODO's are done but did not meet the minimum word count
| Most TODO's are done
| N/A
| Unable to test or Minimum standards were not meet
|===

== Security

All code must conform to the following standards.

* Students must address all memory leaks
* Students must address any double free errors
* Students must not have any dangling pointers in their code
* All out of bounds read/write errors must be addressed.

All projects are configured with a debug option that sets the appropriate
compiler flags for you! Make sure and run all your tests under both debug and
release builds.

include::../../../includes/grading-rubric-boiler.adoc[]
