= Project 0
include::../../../includes/attributes-settings.adoc[]

This assignment is intended to serve as a warm up assignment. In this class you
can choose to implement your assignments using any programming language that has
a https://en.wikipedia.org/wiki/Foreign_function_interface[FFI] for C. The only
**officially** supported language is C. All the code examples will be in
C or Rust and the text book is in C. So if you choose to use Java or Python
you are 100% on your own regarding help with bugs and errors and will have to
translate the example code from your instructor and the book into your language
of choice. Also, be aware that some assignments can only be done in C or Rust
due to limitations that higher level languages have.

In order to keep your sanity during the semester you are encouraged to choose
one language now and stick with it for the rest of the semester. This project is
intended to be light weight in order to give you some time to explore using a
programming language of your choice and introduce the default template for the
semester.

Below are some links to help you get started with each language:

* Java - https://docs.oracle.com/javase/7/docs/technotes/guides/jni/spec/intro.html[JNI]
* Python - https://python.readthedocs.io/en/latest/extending/extending.html[extension
modules].
* Rust - https://doc.rust-lang.org/nomicon/ffi.html[FFI]


WARNING: If you use a language other than the officially support languages you
must create your own starter template and have it approved by the instructor.
Choosing unsupported language qualifies you for bonus points on the every
project. So you will have to decide if the risk is worth the reward 😃.