= Project 0
include::../../../includes/attributes-settings.adoc[]

== Overview

This assignment is intended to serve as an introduction to the build tools that
you will be using this semester.  I have created a
https://github.com/shanep/cpp-project-template[template] that will work for all
the projects. This is the only **officially** supported template. If you feel
ambitions you can create your own template using what ever  programming language
and set of tools that you like. However, be aware that some assignments require
you to deal with raw (untyped) memory which languages like python can't do
without diving down into C.

If you want to use a language like https://www.rust-lang.org/[Rust] you must
create your own starter code template that works with the class grading
framework and have it approved by the instructor. Choosing an unsupported
language qualifies you for bonus points on the every project. So you will have
to decide if the risk is worth the reward 😃.

== Learning Outcomes

* 5.4	 Explore compiling and running code on at least 2 different systems
* 5.5	Explore how to setup a continuous integration and testing project

== ✅ Instructor support systems

Your instructor and GA/TA will support the Kount Lab, Onyx and GitHub
codespaces. If you are working in the lab follow the instructions in the
https://github.com/shanep/cpp-project-template/blob/master/README-KOUNT-LAB.md[CS
Lab] document. Otherwise you can use
https://docs.github.com/en/codespaces/getting-started/quickstart[GitHub
Codespaces] to work on your projects.

=== VSCode Notes

The VSCode CMake extension (2023-10-17) does not support all the features of
cmake presets that this project uses so you will need to add the following to
your settings.json file so that the extension does not complain about the
new features we are using.`"cmake.allowUnsupportedPresetsVersions": true`.

* xref:../../teaching/vscode-tips-and-tricks.adoc[VSCode Tips and Tricks]
* https://code.visualstudio.com/docs/getstarted/settings[VSCode Settings]


== Tools

In order to work on all the projects this semester you have several options.
I have listed all the different options that you can use this semester.

. Use https://github.com/features/codespaces[Github Codespaces]
. Install Linux in a <<Virtual Machine>>
. Come in and use the Lab machines directly
. Code remotely using ssh!

=== Native Programming

* Java is cross platform
* This class is not!
* You will be calling system calls directly
* We will be using Linux

== Virtual Machine

One of the biggest barriers to getting started is to get all your tools
installed and configured correctly.  While it is certainly possible to develop
on any platform (Windows, OSX, BSD, etc.), developing on Linux is by far the
quickest and easiest method. Thus, if you want to jump right in and start
writing code without getting all your tools configured and your development
machine is not running Linux you can start developing in a Virtual machine. Once
you get some experience with the tools and process you should be able to setup
any machine to do OS development on.

== Building 🏛

* Your project Must build from the command line
* Your project Must build on onyx AND GitHub codespaces
** Failure to compile on either will result in a 0! 💀

== Memory Tools

We will look at a few open source tools that you can use to help track down and
solve memory errors in C and C{pp}.  Due to the  unsafe nature of these
languages we need to be extra careful not to let latent memory bugs creep into
our code. Luckily, there have been lots of tools developed over the years that
can help us track down these errors.

While it may be tempting to just eschew C and C{pp}  for a more modern language
that has reduced or eliminated these types of errors, that may not always be
practical because of your working domain. For example, some micro controllers
may have an instruction set architecture (ISA) that a newer language such as
Rust can't even generate code for, so your ony choice is to use the software
development kit (SDK) that is provided by the manufacturer which is most
certainly written in C!

Finally, even if everyone in the world stopped creating any *new* projects in C
and C{pp} there are still *billions* of lines of existing C and C{pp} code that
can't be replaced overnight. So the need to maintain, update, and port existing
C and C{pp} code bases will remain an active area of development for the
forseeable future.

=== Address sanitizer

According to the LLVM documentation
https://clang.llvm.org/docs/AddressSanitizer.html[Address Sanitizer] is a fast
memory error detector. It consists of a compiler instrumentation module and a
run-time library. Address sanitizer should
https://www.openwall.com/lists/oss-security/2016/02/17/9[not be used in
production], it is a development tool to help the engineer track down memory
issues when developing code or tracking down elusive bugs.

One of the best uses of address sanitizer is to use it while unit testing your
code to make sure and catch any low hanging fruit. The tool can detect the
following types of bugs:

* Out-of-bounds accesses to heap, stack and globals
* Use-after-free
* Use-after-return (clang flag -fsanitize-address-use-after-return=(never|runtime|always) default:
runtime)
* Enable runtime with: ASAN_OPTIONS=detect_stack_use_after_return=1
* Use-after-scope (clang flag -fsanitize-address-use-after-scope)
* Double-free, invalid free
* Memory leaks (experimental and currently only on linux)

Here is an example of using address sanitizer (from the llvm docs):

[,c]
----
% cat example_UseAfterFree.cc
int main(int argc, char **argv) {
  int *array = new int[100];
  delete [] array;
  return array[argc];  // BOOM
}

# Compile and link
% clang++ -O1 -g -fsanitize=address -fno-omit-frame-pointer example_UseAfterFree.cc
----

=== Valgrind

https://valgrind.org/[Valgrind] is an awesome tool that can detect
https://github.com/google/sanitizers/wiki/AddressSanitizerComparisonOfMemoryTools[most,
but not all], of the same type of errors that Address Sanitizer can. The biggest
difference is Valgrind doesn't have to be compiled into your binary, so if you
don't have the source code to a particular component you can still debug issues
with Valgrind. Valgrind acts as a virtual machine that dynamically recompiles
the code during runtime. This adds considerable overhead to your program and can
slow down execution by as much as 20x. While Valgrind can't detect all errors it
can help you track down read/write errors and memory leaks without having to
recompile your executable. This is nice if you have a nasty bug that only shows
up in a release build but disappears in debug builds.

You should not use Valgrind on executables that are already compiled with
address sanitizer. You will not get _better_ detection it will just slow down
your code even more and make your life more difficult. A good approach is to use
Address Sanitizer on debug builds and Valgrind on release builds where address
sanitizer has been disabled.

After you run your program Valgrind will report any leaks or errors after your
program exits.

[,bash]
----
All heap blocks were freed -- no leaks are possible
ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
----

Anything else in the valgrind output indicates that you have an error and it
must be fixed no matter how minor.

=== Avoid shooting yourself in the foot

One of the easiest ways to prevent memory related errors is to just avoid (to
the greatest extent possible) some of the more dangerous and poorly designed
parts of C and the C standard library. Remember that C was invented in a simpler
time and was a vast improvement over writing raw assembly at the time. So while
some things may seem obvious now, remember we have the advantage of hindsight!

In the last 40+ years much has been learned about writing secure code and we
should take advantage of those lessons learned. While it would be great to just
remove all the legacy cruft and start new, there is simply too much code in the
world that still depends on some unsafe and poorly designed API's. So while we
can't remove the old cruft, we can still avoid using anything dangerous in any
*new* code that is written.

== Cross Platform Development

While the https://github.com/shanep/cpp-project-template[project template] is
configured to download and install some of the required dependencies each
operating system still needs to have some tools installed to proceed. The
following sections will help you install the required dependencies for each
operating system. Every Semester new issues pop up because of software upgrades
and other changes that are outside of your instructors control so if you
encounter any errors please let your instructor know what you did to fix the
problem so this section can be updated for other students 😃.

WARNING: The systems listed below have been tested by your instructor to work at one
point in time. However, due to the high number of permutations that students
personal systems can come in all systems listed below are **not supported**. If
you can not get your personal system to work then you will need to work in
either codespaces or in the CS Lab.

=== Conditional Compilation

Take a look at the provided `src/lab.cpp` and notice the code that looks similar
to what is show below. This is called a pre-processor directive and allows you
to change what code is compiled based on the the operating system you are
targeting. If you want to create a process on linux you would call
https://man7.org/linux/man-pages/man2/fork.2.html[fork]/https://man7.org/linux/man-pages/man3/exec.3.html[exec].
on windows you would need to call https://learn.microsoft.com/en-us/windows/win32/procthread/creating-processes[Create Process].
Pre-processor directives allow you to have code that supports both operating
systems in the same file which can help reduce overall code maintenance at the
system level.

As an example:

```C
#ifdef __linux__
    //linux code goes here
#leif _WIN32
    // windows code goes here
#else

#endif
```

=== Fedora 38+

* sudo dnf group install "Development Tools"
* sudo dnf install libasan lcov readline gtest-devel gtest

=== Windows 11+

* Install https://visualstudio.microsoft.com/downloads/[Visual Studio 2022]
  Community Edition Select "Desktop development with C++" when prompted.
* https://learn.microsoft.com/en-us/cpp/build/cmake-projects-in-visual-studio?view=msvc-170[Learn about cmake in VS2022+]

=== MacOS 13.5.2+

* Install https://brew.sh/[homebrew]
* Install https://apps.apple.com/us/app/xcode/id497799835?mt=12[Xcode]
* xcode-select -install to install Command Line Tools.
* brew install cmake googletest

=== Ubuntu 22.04 +

* sudo apt-get upgrade
* sudo apt install build-essential manpages-dev
* sudo snap install cmake --classic
* sudo apt-get install git
* sudo apt-get install libreadline-dev

== ❌ Untested Systems

The following systems have been deprecated and are no longer tested or supported.
If you are running one of the systems below you should upgrade to a more recent
system.

* Windows 10
* Ubuntu 20.04

== Task 1 - Fix Issues

You need to fix all the issues in the project template. There should be not
build warnings, not disabled tests, and everything should pass.

== Task 2 - Code coverage

Add enough tests beyond what the professor has given you to get to 100% code
coverage. You are not expected to have 100% code coverage for all your projects
(see the grading rubric) but for this simple intro it is trivial to get to 100%.