= Grading Rubric
include::../../includes/attributes-settings.adoc[]

Grades for programming projects will be assigned according to the rubric below.
Each criterion is clearly detailed in the following sections. Make sure and read
through each section as examples are given for each criterion.

== Minimum standards

Your code must meet the two minimum standards of compiling and correctness in
order to be graded. If your program fails to meet these standards it will not be
graded and a score of 0 will be assigned.

=== Compiling

Unless otherwise stated all code must compile and run on the department's
computers in the Kount Computer Lab (CCP241) and using github codespaces. You
are responsible for ensuring your code compiles in both locations. You can
access the lab computers remotely via ssh or you can go to the lab and use a
workstation directly. https://github.com/features/codespaces[GitHub Codespaces]
is free to use for up to 60 hours per month and can be accessed with any modern
browser.

All code will be compiled and tested on the command line using the scripts
provided. Your instructor or teaching assistant will *not* use an IDE to build
and test your code. While you are welcome to use any IDE you wish to develop
your code it is strongly recommended that you compile and test your code using
the terminal to ensure you have not introduced any IDE specific dependencies on
accident.

All Header files and interfaces must be implemented as specified. You are not
allowed to change the header files in any way. Header files will be reset to
their default state when grading.

== Grading Rubric

|===
| Criterion | Percentage | Expert (1) | Proficient (.8) | Apprentice (.7) | Novice (0)

| Testing
| 60%
| Passes 100% of instructor test suite
| Passes between 90% and 99% of instructor test suite
| Passes 89% or less of instructor test suite
| Unable to test or Minimum standards were not meet.

| Code Quality
| 20%
| No issues with code quality
| One issue
| Two issues
| More than two issues or Minimum standards were not meet.

| Documentation
| 10%
| Perfect documentation
| One or two issues
| Three or four issues
| No documentation was done or Minimum standards were not meet

| Retrospective
| 10%
| ALL TODO's are done and minimum word count was met
| ALL TODO's are done but did not meet the minimum word count
| Retrospective is present but not all TODO's are complete
| Retrospective was not complete or Minimum standards were not meet


|===


include::../../includes/grading-rubric-boiler.adoc[]
