= C++ for Engineers
include::../../includes/attributes-settings.adoc[]

**CS 117 C++ for Engineers (3-0-3)(F,S)** An introductory course in computer
programming using C+\+. Topics include: scalar types; aggregate types; reference
types; statements; expressions; functions; and a brief introduction to classes
and objects. Emphasis is on: implementing given algorithms for numerical,
scientific, and engineering applications. PREREQ: MATH170

== Topics

[cols="~,10"]
|===
|Topic | #Weeks

| **Introduction to C++ (ch1)**, Programming Basics, Comments and whitespace, Errors and warnings, General computer knowledge | 1
| **Variables / Assignments (ch2)**, Types, Identifiers, Arithmetic expressions, Floating point numbers, Strings, Numeric data types, Auto (since C++11) | 2
| **Branches (ch3)**, if-else branches, switch statements, conditional expressions, detecting ranges, logical operators | 2
| **Loops (ch4)**, while loops, for loops, nested loops, break and continue, scoping  | 2
| **User-Defined Functions (ch5)**, Reasons for defining functions, Mathematical functions, Unit testing, Pass by reference, Functions with string/vector parameters | 2
| **Arrays / Vectors (ch6)**,  Iterating through vectors, Vector resize, Vector push_back, two-dimensional arrays, Char arrays / C strings | 2
| **Objects and Classes (ch7)**, Using a class, Defining a class, Mutators, accessors, and private helpers  | 1
| **Streams (ch8)**, Input and Output streams, saving and opening files| 1
| Final Exam | 1
|===


== Required Materials/Texts

* Textbook: zyBooks -  Sign up link is in canvas (**required**)
* xref:grading-rubric.adoc[Grading Rubric]
* https://github.com/BoiseState/CS117-resources[Code Examples]

We will be using zyBooks as our textbook. You should be prompted to sign up for
the book when you complete the first assignment that is linked in canvas. Do not
go to the zyBooks website and create a new account you **must** sign up through
canvas so that your progress is properly recorded.

== Course Learning Outcomes

By the end of this course the student should have achieved the following course
learning outcomes.

[%header,format=csv]
[cols="10,~,15,15"]
|===
include::learning-objectives.csv[]
|===

* https://cft.vanderbilt.edu/guides-sub-pages/blooms-taxonomy/[Blooms Taxonomy]
* https://tips.uark.edu/blooms-taxonomy-verb-chart/[Booms Taxonomy of Verbs]

== Assessments

Your final grade will be calculated with the following weights in canvas.

* Quizzes - 30%
* Projects - 40%
* Textbook Activities - 10%
* Class Participation - 5%
* Final Exam - 15%

=== Quizzes

There will be several quizzes over the assigned reading and general C++
programming during the semester. The quizzes are open notes and open book and
must be done individually.

=== Projects

There are several individual projects this semester. All Projects will be graded
with the xref:grading-rubric.adoc[project grading rubric].

* https://github.com/shanep/cs117-p1-starter[Project 1] - This project is the
standard "Hello World" project to get you started using a programming editor
and compiler!
* https://github.com/shanep/cs117-p2-starter[Project 2] - This project will
allow the student to practice using variables, assignments, simple branching and
convert a scientific formula to code.
* https://github.com/shanep/cs117-p3-starter[Project 3] - This project will
allow the student to understand how to use statements, expressions and loops
* https://github.com/shanep/cs117-p4-starter[Project 4] - This project will
allow the student to practice using functions.
* https://github.com/shanep/cs117-p5-starter[Project 5] - This project will
allow students to practice classes and objects

=== Textbook Activities

We will be using an interactive textbook this semester and your progress through
the textbook will be tracked and reported back to canvas

=== Class Participation

Students are expected to attend class regularly, participate actively in the
classroom, asking and answering questions on the class discussion board, taking
advantage of office hours, and reaching out to the instructor as needed.

=== Final Exam

The final exam will cover all the assigned reading and labs and will be a
multiple choice exam that is closed book closed notes.

include::../../includes/syllabus-boiler.adoc[]

== Tentative Schedule (Fall)

[%header,format=csv]
[cols="10,~,~,~"]
|===
include::schedule.csv[]
|===